name: Lint & Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekker ut repoet
        uses: actions/checkout@v4

      - name: Setter opp Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Installerer avhengigheter
        run: npm install

      - name: Kjører ESLint
        run: npm run lint

      - name: Bygger TypeScript-koden
        run: npm run build

      - name: Sjekker at `dist/` finnes
        run: test -d dist || (echo "❌ Build mangler, sjekk TypeScript-feil!" && exit 1)
